/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LinksRouteImport } from './routes/links'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinksNewRouteImport } from './routes/links.new'
import { Route as LinksLinkIdRouteImport } from './routes/links.$linkId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksNewRoute = LinksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LinksRoute,
} as any)
const LinksLinkIdRoute = LinksLinkIdRouteImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => LinksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/links': typeof LinksRouteWithChildren
  '/security': typeof SecurityRoute
  '/users': typeof UsersRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/links/new': typeof LinksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/links': typeof LinksRouteWithChildren
  '/security': typeof SecurityRoute
  '/users': typeof UsersRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/links/new': typeof LinksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/links': typeof LinksRouteWithChildren
  '/security': typeof SecurityRoute
  '/users': typeof UsersRoute
  '/links/$linkId': typeof LinksLinkIdRoute
  '/links/new': typeof LinksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/links'
    | '/security'
    | '/users'
    | '/links/$linkId'
    | '/links/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/links'
    | '/security'
    | '/users'
    | '/links/$linkId'
    | '/links/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/links'
    | '/security'
    | '/users'
    | '/links/$linkId'
    | '/links/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  LinksRoute: typeof LinksRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/new': {
      id: '/links/new'
      path: '/new'
      fullPath: '/links/new'
      preLoaderRoute: typeof LinksNewRouteImport
      parentRoute: typeof LinksRoute
    }
    '/links/$linkId': {
      id: '/links/$linkId'
      path: '/$linkId'
      fullPath: '/links/$linkId'
      preLoaderRoute: typeof LinksLinkIdRouteImport
      parentRoute: typeof LinksRoute
    }
  }
}

interface LinksRouteChildren {
  LinksLinkIdRoute: typeof LinksLinkIdRoute
  LinksNewRoute: typeof LinksNewRoute
}

const LinksRouteChildren: LinksRouteChildren = {
  LinksLinkIdRoute: LinksLinkIdRoute,
  LinksNewRoute: LinksNewRoute,
}

const LinksRouteWithChildren = LinksRoute._addFileChildren(LinksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  LinksRoute: LinksRouteWithChildren,
  SecurityRoute: SecurityRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
